# Generated by Django 3.0.6 on 2020-05-31 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='CrmEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='ФИО клиента')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('opportunity', models.FloatField(default=0)),
                ('opportunity_currency', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='StageContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(default='lead', max_length=20, verbose_name='Сущность контейнера')),
                ('title', models.CharField(max_length=50, verbose_name='Название контейнера стадий')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('crmentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.CrmEntity')),
                ('title', models.CharField(default='Лид №<built-in function id>', max_length=50, verbose_name='Название лида')),
                ('_stage_id', models.IntegerField(default=0, verbose_name='Стадия сделки')),
            ],
            bases=('core.crmentity',),
        ),
        migrations.CreateModel(
            name='StageId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#ffffff', max_length=6, verbose_name='Цвет')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.StageContainer')),
            ],
        ),
    ]
