# Generated by Django 3.0.6 on 2020-05-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='_stage_id',
            field=models.IntegerField(default=0, verbose_name='Стадия сделки'),
        ),
    ]
