# Generated by Django 3.0.6 on 2020-06-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='title',
            new_name='_title',
        ),
    ]
