# Generated by Django 3.0.6 on 2020-05-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead__stage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=20, verbose_name='Сущность контейнера')),
                ('title', models.CharField(max_length=50, verbose_name='Название контейнера стадий')),
                ('color', models.CharField(default='#ffffff', max_length=6, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='StageId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.StageContainer')),
            ],
        ),
    ]
