# Generated by Django 3.0.6 on 2020-06-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200602_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageid',
            name='name',
            field=models.CharField(default='ti', max_length=30, verbose_name='Название стадии'),
        ),
        migrations.AlterField(
            model_name='stagecontainer',
            name='entity',
            field=models.CharField(default='deal', max_length=20, verbose_name='Сущность контейнера'),
        ),
    ]
