# Generated by Django 3.0.6 on 2020-06-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200603_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmentity',
            name='opportunity_currency',
        ),
        migrations.AddField(
            model_name='crmentity',
            name='short_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='_stage_id',
            field=models.IntegerField(default=1, verbose_name='Стадия сделки'),
        ),
    ]
