# Generated by Django 3.0.6 on 2020-06-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200603_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='asd',
            field=models.TextField(default='updateDatabase'),
        ),
    ]
