# Generated by Django 3.0.6 on 2020-06-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lead_asd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='asd',
        ),
    ]
