# Generated by Django 3.0.6 on 2020-06-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200604_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crmentity',
            old_name='contact',
            new_name='_contact',
        ),
        migrations.RenameField(
            model_name='crmentity',
            old_name='description',
            new_name='_description',
        ),
        migrations.RenameField(
            model_name='crmentity',
            old_name='email',
            new_name='_email',
        ),
        migrations.RenameField(
            model_name='crmentity',
            old_name='opportunity',
            new_name='_opportunity',
        ),
        migrations.RenameField(
            model_name='crmentity',
            old_name='phone_number',
            new_name='_phone_number',
        ),
        migrations.RenameField(
            model_name='crmentity',
            old_name='short_description',
            new_name='_short_description',
        ),
    ]
