# Generated by Django 3.0.6 on 2020-06-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200604_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagecontainer',
            old_name='entity',
            new_name='_entity',
        ),
        migrations.RenameField(
            model_name='stagecontainer',
            old_name='title',
            new_name='_title',
        ),
        migrations.RenameField(
            model_name='stageid',
            old_name='color',
            new_name='_color',
        ),
        migrations.RenameField(
            model_name='stageid',
            old_name='container',
            new_name='_container',
        ),
        migrations.RenameField(
            model_name='stageid',
            old_name='name',
            new_name='_name',
        ),
    ]
