# Generated by Django 3.0.6 on 2020-06-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_crmentity__contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmentity',
            name='_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Contact'),
        ),
    ]
