# Generated by Django 3.0.6 on 2020-06-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_crmentity__contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='_description',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='_first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='_last_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='_phone_number',
        ),
        migrations.RemoveField(
            model_name='crmentity',
            name='_short_description',
        ),
        migrations.AddField(
            model_name='contact',
            name='_type',
            field=models.CharField(default='Покупатель', max_length=30, verbose_name='Тип клиента'),
        ),
    ]
